---

- name: join workers
  vars:
    join_command: "{{ lookup('file', './current_cluster/kubeadm-init.txt') }}"
  shell: "{{ join_command.stdout_lines[-1] }}"
  register: out

- debug: var=out.stdout_lines

...
